### Import Libraries

In [1]:
import pandas as pd
!pip install mlxtend
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

Requirement already satisfied: mlxtend in c:\users\mayu\downloads\anaconda\lib\site-packages (0.19.0)
Requirement already satisfied: numpy>=1.16.2 in c:\users\mayu\downloads\anaconda\lib\site-packages (from mlxtend) (1.21.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\mayu\downloads\anaconda\lib\site-packages (from mlxtend) (3.3.4)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\mayu\downloads\anaconda\lib\site-packages (from mlxtend) (0.23.1)
Requirement already satisfied: setuptools in c:\users\mayu\downloads\anaconda\lib\site-packages (from mlxtend) (52.0.0.post20210125)
Requirement already satisfied: joblib>=0.13.2 in c:\users\mayu\downloads\anaconda\lib\site-packages (from mlxtend) (1.0.1)
Requirement already satisfied: pandas>=0.24.2 in c:\users\mayu\downloads\anaconda\lib\site-packages (from mlxtend) (1.2.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\mayu\downloads\anaconda\lib\site-packages (from mlxtend) (1.6.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\mayu\downloads\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in c:\users\mayu\downloads\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\mayu\downloads\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\mayu\downloads\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\mayu\downloads\anaconda\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: six in c:\users\mayu\downloads\anaconda\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\mayu\downloads\anaconda\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\mayu\downloads\anaconda\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)

***Book Dataset***

In [2]:
book = pd.read_csv("book.csv")
book.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0

### Apriori Algorithm

In [3]:
frequent_itemsets_1 = apriori(book, min_support=0.1, use_colnames=True)
frequent_itemsets_1

    support                       itemsets
0    0.4230                     (ChildBks)
1    0.2475                     (YouthBks)
2    0.4310                      (CookBks)
3    0.2820                     (DoItYBks)
4    0.2145                       (RefBks)
5    0.2410                       (ArtBks)
6    0.2760                      (GeogBks)
7    0.1135                     (ItalCook)
8    0.1085                     (Florence)
9    0.1650           (YouthBks, ChildBks)
10   0.2560            (ChildBks, CookBks)
11   0.1840           (ChildBks, DoItYBks)
12   0.1515             (ChildBks, RefBks)
13   0.1625             (ChildBks, ArtBks)
14   0.1950            (ChildBks, GeogBks)
15   0.1620            (YouthBks, CookBks)
16   0.1155           (YouthBks, DoItYBks)
17   0.1010             (YouthBks, ArtBks)
18   0.1205            (YouthBks, GeogBks)
19   0.1875            (DoItYBks, CookBks)
20   0.1525              (RefBks, CookBks)
21   0.1670              (ArtBks, CookBks)
22   0.1925             (GeogBks, CookBks)
23   0.1135            (ItalCook, CookBks)
24   0.1055             (DoItYBks, RefBks)
25   0.1235             (DoItYBks, ArtBks)
26   0.1325            (GeogBks, DoItYBks)
27   0.1105              (GeogBks, RefBks)
28   0.1275              (GeogBks, ArtBks)
29   0.1290  (YouthBks, ChildBks, CookBks)
30   0.1460  (ChildBks, DoItYBks, CookBks)
31   0.1225    (ChildBks, RefBks, CookBks)
32   0.1265    (ChildBks, ArtBks, CookBks)
33   0.1495   (ChildBks, GeogBks, CookBks)
34   0.1045  (GeogBks, ChildBks, DoItYBks)
35   0.1020    (ChildBks, GeogBks, ArtBks)
36   0.1015    (DoItYBks, ArtBks, CookBks)
37   0.1085   (GeogBks, DoItYBks, CookBks)
38   0.1035     (GeogBks, ArtBks, CookBks)

### Rule 1 ###

In [4]:
rule_1 = association_rules(frequent_itemsets_1, metric="lift", min_threshold=0.7)
rule_1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(YouthBks),(ChildBks),0.2475,0.4230,0.1650,0.666667,1.576044,0.060308,1.731000
1,(ChildBks),(YouthBks),0.4230,0.2475,0.1650,0.390071,1.576044,0.060308,1.233750
2,(ChildBks),(CookBks),0.4230,0.4310,0.2560,0.605201,1.404179,0.073687,1.441240
3,(CookBks),(ChildBks),0.4310,0.4230,0.2560,0.593968,1.404179,0.073687,1.421069
4,(ChildBks),(DoItYBks),0.4230,0.2820,0.1840,0.434988,1.542511,0.064714,1.270770
...,...,...,...,...,...,...,...,...,...
95,"(GeogBks, CookBks)",(ArtBks),0.1925,0.2410,0.1035,0.537662,2.230964,0.057107,1.641657
96,"(ArtBks, CookBks)",(GeogBks),0.1670,0.2760,0.1035,0.619760,2.245509,0.057408,1.904063
97,(GeogBks),"(ArtBks, CookBks)",0.2760,0.1670,0.1035,0.375000,2.245509,0.057408,1.332800
98,(ArtBks),"(GeogBks, CookBks)",0.2410,0.1925,0.1035,0.429461,2.230964,0.057107,1.415327
99,(CookBks),"(GeogBks, ArtBks)",0.4310,0.1275,0.1035,0.240139,1.883445,0.048547,1.148237

In [5]:
rule_1.sort_values('lift',ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
29,(CookBks),(ItalCook),0.4310,0.1135,0.1135,0.263341,2.320186,0.064582,1.203406
28,(ItalCook),(CookBks),0.1135,0.4310,0.1135,1.000000,2.320186,0.064582,inf
77,"(ChildBks, ArtBks)",(GeogBks),0.1625,0.2760,0.1020,0.627692,2.274247,0.057150,1.944628
80,(GeogBks),"(ChildBks, ArtBks)",0.2760,0.1625,0.1020,0.369565,2.274247,0.057150,1.328448
86,(ArtBks),"(DoItYBks, CookBks)",0.2410,0.1875,0.1015,0.421162,2.246196,0.056313,1.403674
83,"(DoItYBks, CookBks)",(ArtBks),0.1875,0.2410,0.1015,0.541333,2.246196,0.056313,1.654797
96,"(ArtBks, CookBks)",(GeogBks),0.1670,0.2760,0.1035,0.619760,2.245509,0.057408,1.904063
97,(GeogBks),"(ArtBks, CookBks)",0.2760,0.1670,0.1035,0.375000,2.245509,0.057408,1.332800
95,"(GeogBks, CookBks)",(ArtBks),0.1925,0.2410,0.1035,0.537662,2.230964,0.057107,1.641657
98,(ArtBks),"(GeogBks, CookBks)",0.2410,0.1925,0.1035,0.429461,2.230964,0.057107,1.415327
53,"(ChildBks, CookBks)",(RefBks),0.2560,0.2145,0.1225,0.478516,2.230842,0.067588,1.506277
56,(RefBks),"(ChildBks, CookBks)",0.2145,0.2560,0.1225,0.571096,2.230842,0.067588,1.734652
76,"(ChildBks, GeogBks)",(ArtBks),0.1950,0.2410,0.1020,0.523077,2.170444,0.055005,1.591452
81,(ArtBks),"(ChildBks, GeogBks)",0.2410,0.1950,0.1020,0.423237,2.170444,0.055005,1.395719
85,(DoItYBks),"(ArtBks, CookBks)",0.2820,0.1670,0.1015,0.359929,2.155264,0.054406,1.301418
84,"(ArtBks, CookBks)",(DoItYBks),0.1670,0.2820,0.1015,0.607784,2.155264,0.054406,1.830626
68,(GeogBks),"(ChildBks, CookBks)",0.2760,0.2560,0.1495,0.541667,2.115885,0.078844,1.623273
65,"(ChildBks, CookBks)",(GeogBks),0.2560,0.2760,0.1495,0.583984,2.115885,0.078844,1.740319
91,(GeogBks),"(DoItYBks, CookBks)",0.2760,0.1875,0.1085,0.393116,2.096618,0.056750,1.338806
90,"(DoItYBks, CookBks)",(GeogBks),0.1875,0.2760,0.1085,0.578667,2.096618,0.056750,1.718354

In [6]:
rule_1[rule_1.lift>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(YouthBks),(ChildBks),0.2475,0.4230,0.1650,0.666667,1.576044,0.060308,1.731000
1,(ChildBks),(YouthBks),0.4230,0.2475,0.1650,0.390071,1.576044,0.060308,1.233750
2,(ChildBks),(CookBks),0.4230,0.4310,0.2560,0.605201,1.404179,0.073687,1.441240
3,(CookBks),(ChildBks),0.4310,0.4230,0.2560,0.593968,1.404179,0.073687,1.421069
4,(ChildBks),(DoItYBks),0.4230,0.2820,0.1840,0.434988,1.542511,0.064714,1.270770
...,...,...,...,...,...,...,...,...,...
95,"(GeogBks, CookBks)",(ArtBks),0.1925,0.2410,0.1035,0.537662,2.230964,0.057107,1.641657
96,"(ArtBks, CookBks)",(GeogBks),0.1670,0.2760,0.1035,0.619760,2.245509,0.057408,1.904063
97,(GeogBks),"(ArtBks, CookBks)",0.2760,0.1670,0.1035,0.375000,2.245509,0.057408,1.332800
98,(ArtBks),"(GeogBks, CookBks)",0.2410,0.1925,0.1035,0.429461,2.230964,0.057107,1.415327
99,(CookBks),"(GeogBks, ArtBks)",0.4310,0.1275,0.1035,0.240139,1.883445,0.048547,1.148237

### Apriori Algorithm

In [7]:
frequent_itemsets_2 = apriori(book, min_support=0.2, use_colnames=True)
frequent_itemsets_2

   support             itemsets
0   0.4230           (ChildBks)
1   0.2475           (YouthBks)
2   0.4310            (CookBks)
3   0.2820           (DoItYBks)
4   0.2145             (RefBks)
5   0.2410             (ArtBks)
6   0.2760            (GeogBks)
7   0.2560  (ChildBks, CookBks)

### Rule 2

In [8]:
rule_2 = association_rules(frequent_itemsets_2, metric="lift", min_threshold=1)
rule_2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ChildBks),(CookBks),0.423,0.431,0.256,0.605201,1.404179,0.073687,1.441240
1,(CookBks),(ChildBks),0.431,0.423,0.256,0.593968,1.404179,0.073687,1.421069

### Apriori Algorithm

In [9]:
frequent_itemsets_3 = apriori(book, min_support=0.3, use_colnames=True)
frequent_itemsets_3

   support    itemsets
0    0.423  (ChildBks)
1    0.431   (CookBks)

### Rule 3

In [10]:
rule_3 = association_rules(frequent_itemsets_3, metric="lift", min_threshold=0.7)
rule_3

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

### Apriori Algorithm

In [11]:
frequent_itemsets_4 = apriori(book, min_support=0.4, use_colnames=True)
frequent_itemsets_4

   support    itemsets
0    0.423  (ChildBks)
1    0.431   (CookBks)

### Rule 4

In [12]:
rule_4 = association_rules(frequent_itemsets_4, metric="lift", min_threshold=0.1)
rule_4

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

***Movies Dataset***

In [13]:
Movies = pd.read_csv("Movies.csv")
Movies.head()

,V1,V2,V3,V4,V5,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile
0,Sixth Sense,LOTR1,Harry Potter1,Green Mile,LOTR2,1,0,1,1,0,1,0,0,0,1
1,Gladiator,Patriot,Braveheart,NaN,NaN,0,1,0,0,1,0,0,0,1,0
2,LOTR1,LOTR2,NaN,NaN,NaN,0,0,1,0,0,1,0,0,0,0
3,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
4,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0

### Pre-Processing
As the data is not in transaction formation 
We are using transaction Encoder

In [14]:
df=pd.get_dummies(Movies)
df.head()

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile,...,V2_LOTR,V2_LOTR1,V2_LOTR2,V2_Patriot,V3_Braveheart,V3_Gladiator,V3_Harry Potter1,V3_Sixth Sense,V4_Green Mile,V5_LOTR2
0,1,0,1,1,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,1,1
1,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
2,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [15]:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
frequent_itemsets

    support                                        itemsets
0       0.6                                   (Sixth Sense)
1       0.7                                     (Gladiator)
2       0.6                                       (Patriot)
3       0.6                                  (V1_Gladiator)
4       0.6                                    (V2_Patriot)
5       0.5                        (Gladiator, Sixth Sense)
6       0.6                            (Patriot, Gladiator)
7       0.6                       (V1_Gladiator, Gladiator)
8       0.6                         (V2_Patriot, Gladiator)
9       0.6                         (Patriot, V1_Gladiator)
10      0.6                           (V2_Patriot, Patriot)
11      0.6                      (V2_Patriot, V1_Gladiator)
12      0.6              (Patriot, V1_Gladiator, Gladiator)
13      0.6                (V2_Patriot, Patriot, Gladiator)
14      0.6           (V2_Patriot, V1_Gladiator, Gladiator)
15      0.6             (V2_Patriot, Patriot, V1_Gladiator)
16      0.6  (V2_Patriot, V1_Gladiator, Patriot, Gladiator)

In [16]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.4
1,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.8
2,(Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
3,(Gladiator),(Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
4,(V1_Gladiator),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
5,(Gladiator),(V1_Gladiator),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
6,(V2_Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
7,(Gladiator),(V2_Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
8,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
9,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
10,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
11,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
12,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
13,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
14,"(Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
15,"(Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
16,"(Gladiator, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
17,(Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
18,(V1_Gladiator),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
19,(Gladiator),"(Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
20,"(V2_Patriot, Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
21,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
22,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
23,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
24,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
25,(Gladiator),"(V2_Patriot, Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
26,"(V2_Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
27,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
28,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
29,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
30,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
31,(Gladiator),"(V2_Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
32,"(V2_Patriot, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
33,"(V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
34,"(Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
35,(V2_Patriot),"(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
36,(Patriot),"(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
37,(V1_Gladiator),"(V2_Patriot, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
38,"(V2_Patriot, Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
39,"(Gladiator, V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
40,"(V2_Patriot, Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
41,"(Gladiator, Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
42,"(V2_Patriot, V1_Gladiator)","(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
43,"(V2_Patriot, Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
44,"(V2_Patriot, Gladiator)","(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
45,"(Patriot, V1_Gladiator)","(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
46,"(Gladiator, V1_Gladiator)","(V2_Patriot, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
47,"(Patriot, Gladiator)","(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
48,(V2_Patriot),"(Gladiator, Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
49,(V1_Gladiator),"(V2_Patriot, Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
50,(Patriot),"(Gladiator, V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
51,(Gladiator),"(V2_Patriot, Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8

In [17]:
rules.sort_values('lift',ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
21,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
43,"(V2_Patriot, Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
23,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
24,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
45,"(Patriot, V1_Gladiator)","(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
27,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
28,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
29,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
30,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
32,"(V2_Patriot, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
33,"(V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
34,"(Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
35,(V2_Patriot),"(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
36,(Patriot),"(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
37,(V1_Gladiator),"(V2_Patriot, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
44,"(V2_Patriot, Gladiator)","(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
39,"(Gladiator, V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
40,"(V2_Patriot, Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
41,"(Gladiator, Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf

In [18]:
rules[rules.lift>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.4
1,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.8
2,(Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
3,(Gladiator),(Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
4,(V1_Gladiator),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
5,(Gladiator),(V1_Gladiator),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
6,(V2_Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
7,(Gladiator),(V2_Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
8,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
9,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
10,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
11,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
12,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
13,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
14,"(Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
15,"(Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
16,"(Gladiator, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
17,(Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
18,(V1_Gladiator),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
19,(Gladiator),"(Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
20,"(V2_Patriot, Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
21,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
22,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
23,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
24,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
25,(Gladiator),"(V2_Patriot, Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
26,"(V2_Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
27,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
28,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
29,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
30,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
31,(Gladiator),"(V2_Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
32,"(V2_Patriot, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
33,"(V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
34,"(Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
35,(V2_Patriot),"(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
36,(Patriot),"(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
37,(V1_Gladiator),"(V2_Patriot, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
38,"(V2_Patriot, Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
39,"(Gladiator, V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
40,"(V2_Patriot, Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
41,"(Gladiator, Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
42,"(V2_Patriot, V1_Gladiator)","(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
43,"(V2_Patriot, Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
44,"(V2_Patriot, Gladiator)","(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
45,"(Patriot, V1_Gladiator)","(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
46,"(Gladiator, V1_Gladiator)","(V2_Patriot, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
47,"(Patriot, Gladiator)","(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
48,(V2_Patriot),"(Gladiator, Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
49,(V1_Gladiator),"(V2_Patriot, Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
50,(Patriot),"(Gladiator, V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
51,(Gladiator),"(V2_Patriot, Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8